print("Here you will make a recipe fit to feed a king")
print()
name = input("First things first, what's your name?: ")
food = input("Name a type of cuisine?: ")
plant = input("Name a type of plant: ")
cooking_method = input("Name your go-to cooking method: ")
description_word = input("In one word, how would you described burnt food: ")
household_item = input("Name a household item: ")
print()
print("Our Menu")
print(name, "your meal fit to feed a queen will be", cooking_method, food, "with", description_word, plant, "on a bed of", household_item, "hehe enjoy!")